### ISSUE TITLE
No such file or directory @ rb_sysopen - config/env/production.yml

### ISSUE THREAD

**Issue by Pr00xxy** [DivanteLtd/anonymizer#3]
Running as instructed 
`RUBY_ENV=production bundle exec rake project:anonymize[example]`
where example is replaced with the json file name returns the following

`Errno::ENOENT: No such file or directory @ rb_sysopen - config/env/production.yml
/home/ubuntu/anonymizer-master/init.rb:22:in `<top (required)>'
/home/ubuntu/anonymizer-master/Rakefile:1:in `require'
/home/ubuntu/anonymizer-master/Rakefile:1:in `<top (required)>'
/home/ubuntu/anonymizer-master/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
`

Looks like I'm missing config/env/production.yml somehow

**Comment by Pr00xxy** [comment]
Is this repo still being maintained?
Looks promising and perfect for magento 1.9 and 2.x but if there is no one maintaining i will have to look into other solutions

**Comment by dannevang** [comment]
@Pr00xxy Did you solve this? I'm seeing the same issue and is unsure what to add in the config yaml files needed.

**Comment by mkoszut** [comment]
@Pr00xxy @dannevang This week I will solve this issue.

**Comment by Lynoure** [comment]
I think the configuration file goes there. Remember to lint it e.g. with yamllint first, and the error messages Psych gives are sometimes a bit misleading.

**Comment by dannevang** [comment]
@Lynoure question is which config? According to the readme the project config goes to config/project/ folder. 

There is no definition I can find of which enviromental variable that is needed in the /config/env/ folder. But from the code I can see that the default is a development.yml and a production.yml is also expected according to the readme.

**Comment by Lynoure** [comment]
I am still in figuring this out as well. Fortunate timing. I guess GDPR drives people to similar actions :)

It seems to choose the name of the file base on what's in RUBY_ENV, and if none is given, it defaults to development.yml. Continuing to explore.

**Comment by Lynoure** [comment]
At least: 
tmp_path

(continuing)

**Comment by mkoszut** [comment]
Example configuration:
```
logger:
  enabled: true
dump_server:
  host: example.com
  user: mkoszut
  port: "622"
  passphrase:
  path: /home/users/mkoszut
database:
  user: anonymizer
  host: localhost
  pass: 
web_data_path: ./web/data
tmp_path: /tmp
cap:
  ssh_options:
    keys: 
      - /home/mkoszutowski/.ssh/id_rsa
```
